### ISSUE TITLE
Why the performance of convolution attain about 50% of the peak GFLOPS on some ARM processors?

### ISSUE THREAD

**Issue by wpy1368064015** [libxsmm/libxsmm-dnn#16]
This a good job! And we are interested in the work in paper "Tensor Processing Primitives: A Programming Abstraction forEfficiency and Portability in Deep Learning Workloads", we utilize the source code from this project to evaluate the conv performance on some ARM-based processors, but the performance of convolution attains about 50% of the peak GFLOPS.  Is there some configurations to attain the high-performance?

**Comment by hfp** [comment]
Can you elaborate on which ARM processors your are interested?

We have several [code-paths](https://github.com/libxsmm/libxsmm/blob/main/include/libxsmm_cpuid.h#L43) in our library and efficiency can vary based on processor features present/utilized:

* AArch64 v8.1 (Baseline)
* AArch64 v8.2
* Apple M1
* SVE 128 bit
* SVE 256 bit
* Neoverse V1 and Graviton 3
* SVE 512 bit
* SVE 512 bit (A64FX)

The listed code-paths are not necessarily utilized depending on the actual kernel. We have more than just GEMM/SMM kernels, namely element-wise kernels.

You can also double-check the chosen code-path on a particular processor using `LIBXSMM_VERBOSE=1` (or higher verbosity).

**Comment by hfp** [comment]
Do you have any more details about processor, tested convolutions, or the test/benchmark itself?

**Comment by wpy1368064015** [comment]
> Do you have any more details about processor, tested convolutions, or the test/benchmark itself?

We test libxsmm's direct convolution on ThunderX2 processors with libxsmm-dnn/tests/conv)/layer_example.c.
The datasets we utilize are convolution layers from resnet-50. We set the number of batch size and CPU cores to be the same.

**Comment by hfp** [comment]
> We test libxsmm's direct convolution on ThunderX2 processor

This processor hits our AArch64 baseline. Running with `LIBXSMM_VERBOSE` environment variable shows `aarch64` at program termination), alternatively, executing `scripts/libxsmm_utilities.py` shows `aarch64` as well. I guess your system should yield 8 FLOPS/cycle (FP32), but you're only getting ~4 like your 50%?

> We set the number of batch size and CPU cores to be the same.

This is alright. I recommend to only use one socket (in case of a dual-socket system). The runner script already sets `OMP_PROC_BIND=close` and `OMP_PLACES=threads`. If the system supports SMT, the full number of threads per socket can be given with `OMP_NUM_THREADS` (and still hitting only one socket).

**Comment by wpy1368064015** [comment]
> > We test libxsmm's direct convolution on ThunderX2 processor
> 
> This processor hits our AArch64 baseline. Running with `LIBXSMM_VERBOSE` environment variable shows `aarch64` at program termination), alternatively, executing `scripts/libxsmm_utilities.py` shows `aarch64` as well. I guess your system should yield 8 FLOPS/cycle (FP32), but you're only getting ~4 like your 50%?
> 
> > We set the number of batch size and CPU cores to be the same.
> 
> This is alright. I recommend to only use one socket (in case of a dual-socket system). The runner script already sets `OMP_PROC_BIND=close` and `OMP_PLACES=threads`. If the system supports SMT, the full number of threads per socket can be given with `OMP_NUM_THREADS` (and still hitting only one socket).

Thanks for you patient reply! As you mentioned before, we use one socket of ThunderX2 processors and utilize OMP_NUM_THREADS to specify the number of threads. However, the performance can not achieve expected GFLOPS(FP32).

**Comment by hfp** [comment]
The ThunderX2 has two NEON pipelines. Your 50% of peak might mean it is only utilizing one of the two NEON pipelines. The "reference implementation" of AArch64 v8.1 comes with one NEON pipeline (like almost all other implementations of v8.1), hence ThunderX2 is likely even more customized (e.g., SMP) such that the related peak performance can be reached "somehow". As pointed out, ThunderX2 implements SMP and your 50% of peak can be related to the SMP-mode (three settings are available at boot time). Perhaps take a [look](https://phoenicselectronics.zendesk.com/hc/en-us/articles/360039106212-How-to-manage-Symmetric-Multi-Threading-on-ThunderX2-systems) and check if you can reach higher efficiency.

**Comment by hfp** [comment]
I am closing this report for now. Please feel free to provide feedback if you get/got to try a different [SMP mode](https://github.com/libxsmm/libxsmm-dnn/issues/16#issuecomment-1463431129). Thank you for your [kind words](https://github.com/libxsmm/libxsmm-dnn/issues/16#issue-1589044753) and let us know if you need assistance!
