### ISSUE TITLE
Why the path to LIBXSMM cannot be a make variable and must be an env variable?

### ISSUE THREAD

**Issue by kvoronin-intel** [libxsmm/libxsmm-dnn#17]
This constitutes an inconvenience for using libxxsmm-dnn in other codes (e.g., building it as a part of custom build of a Python module)

Not sure why we cannot pass LIBXSMMROOT as a variable to make, i.e.:
make ... LIBSXSMMROOT=<path>.

**Comment by hfp** [comment]
Thank you for suggesting this! It's a reasonable change and easy to implement. Though, LIBXSMM-DNN was a break-out from LIBXSMM and the build system does not feature many options when compared to LIBXSMM. It however shares or actually reuses most of LIBXSMM's infrastructure (Makefile.inc, etc). No excuse still, I will implement your suggestion!

**Comment by kvoronin-intel** [comment]
> Thank you for suggesting this! It's a reasonable change and easy to implement. Though, LIBXSMM-DNN was a break-out from LIBXSMM and the build system does not feature many options when compared to LIBXSMM. It however shares or actually reuses most of LIBXSMM's infrastructure (Makefile.inc, etc). No excuse still, I will implement your suggestion!

Actually, I realized that this is not the only issue I am facing. With some more Python APIs I can modify the env prior when calling make (and this resolves the issue while looking clumsy in the code).
What is worse: I'm doing an out-of-tree LIBXSMM build (because it's a part of a build of a Python module) and now when I want to add libxsmm-dnn as another piece of the build, it needs include/ and lib/ but also Makefile.inc and other stuff).

So if you decide to make the Makefile more general, I'd separate libxsmm root with Makefile.inc and utils and libxsmm builddir (which should be by default equal to libxsmm root but allow an option to be overriden)

**Comment by hfp** [comment]
> What is worse: I'm doing an out-of-tree LIBXSMM build...

I think this is a call for documenting such flow (and potentially fixing issues). Building LIBXSMM in an out-of-tree fashion is well exercised. Then, referring to such out-of-tree build should be flawless (via LIBXSMMROOT).

It could be that an out-of-tree build of LIBXSMM does not prepare the target directory for "header-only" (I must check). However, LIBXSMM's supports `make PREFIX=... install` which prepares the install directory for all kinds of use cases including shared and static libraries as well as header-only.

**Comment by kvoronin-intel** [comment]
I've realized that in fact out-of-tree should already work due to
```
DEPENV = $(shell echo "$${LIBXSMMROOT}")
DEPDIR = $(if $(wildcard $(LIBXSMMROOT)),$(LIBXSMMROOT),$(if $(wildcard $(DEPENV)),$(DEPENV),libxsmm))
```
but when I do an out-of-tree LIBXSMM-DNN build, e.g.
```
cd tmp/
export LIBXSMMROOT=<path to libxsmm>
make -f <path to libxsmm-dnn Makefile>  CC=gcc CXX=g++ AVX=2 -j LIBXSMMROOT=<path to libxsmm>
```
I get
```
-rw-rw-r-- 1 kvoronin kvoronin    8 Aug 21 13:25 libxsmm_dnn.a
-rwxrwxr-x 1 kvoronin kvoronin 7192 Aug 21 13:25 libxsmm_dnn.so
```
with 
```
(pt1120) bash-4.2$ cat libxsmm_dnn.a
!<arch>
```
and also incorrect *.so.

Not sure why...

This is with commit 184c1cec525d0664848d0a34835d518694a2c708 of main_stable of libxsmm-dnn (maybe, outdated?)

UPD: Same with c892d6c880ad1028896f91689d638c856e7d96b2 (latest main_stable)
