### ISSUE TITLE
PR #20 broke CI

### ISSUE THREAD

**Issue by rengolin** [libxsmm/libxsmm-dnn#21]
#20 has broken the CI loop.

@hfp

**Comment by alheinecke** [comment]
It seems the PR was not complete, with my Hotfix [3ef7d1d](https://github.com/libxsmm/libxsmm-dnn/commit/3ef7d1d6206fa4b75c9a787e1e2c11aa3e925f60) the problem is reduced to some ICX issue.

**Comment by rengolin** [comment]
Perhaps revert the commit (and fix up) until green?

**Comment by alheinecke** [comment]
The problem is the ICX compiler (and only ICX) and then having undefined symbols when linking. 
@hfp: any update on this?

**Comment by rengolin** [comment]
@hfp can you look at this? It's still broken and reverting the patch (and hotfix) will break compatibility with `libxsmm`.

**Comment by alheinecke** [comment]
In fact that bug seems to be in the Makefile.Inc of the main libxsmm project. Even libxsmm itself built with icx and samples using OpenMP don't work.

**Comment by alheinecke** [comment]
BTW: some folks are running into similar issues, but the entry is not really helping
https://community.intel.com/t5/Intel-oneAPI-Data-Parallel-C/undefined-symbol-tid-addr-bid-addr/m-p/1266855
@hfp: please follow up on what needs to be fixed.

**Comment by rengolin** [comment]
@alheinecke tests still red. :(

**Comment by alheinecke** [comment]
nothing to worried about.... see #23
