### ISSUE TITLE
Some AMX executions fail for various reasons

### ISSUE THREAD

**Issue by alheinecke** [libxsmm/libxsmm-dnn#23]
I fix the compilation with latest Intel Compilers and now CI is working again as expected. Since the CI env was upgraded to SPR, the BF16 code path has changed (from AVX512 emulation to AMX). Now some of the test are failing with Nullpointer kernels and/or code buffer out runs.

**Comment by alheinecke** [comment]
@egeor : when will you have an estimate of what it takes to fix these 4 (for now) failures?

**Comment by egeor** [comment]
Will take a look later this week

**Comment by alheinecke** [comment]
fixed by 6fff2ae9cc8c69be65037f8680351faeb8c1ea78
