### ISSUE TITLE
Validation: tests/conv incorrect results

### ISSUE THREAD

**Issue by hfp** [libxsmm/libxsmm-dnn#3]
To reproduce failures out of scripted execution, a recent feature about [printing the command line](https://github.com/libxsmm/libxsmm/wiki/Validation#reproduce-failures) was used (`LIBXSMM_VERBOSE=4`):

```bash
LIBXSMM_TARGET=hsw ./layer_example 1 7 7 8 2048 512 1 1 3 3 2 F L 0 0 64 64 4
LIBXSMM_TARGET=hsw ./layer_example 1 7 7 8 2048 512 1 1 3 3 2 F L 0 0 64 64 2
LIBXSMM_TARGET=clx ./layer_example 1 7 7 8 2048 512 1 1 3 3 2 F L 0 0 64 64 2
```

**Comment by egeor** [comment]
Commit da4662af4618c512e248f6fac3a43f8717a82af1 should fix these ones

**Comment by hfp** [comment]
@egeor Thank you! Your fix allows the full collection of DeepBench layers to pass our tests.
