### ISSUE TITLE
The Convolution layout Issue 

### ISSUE THREAD

**Issue by wpy1368064015** [libxsmm/libxsmm-dnn#4]
Can libxsmm support the NCHW and KCRS layout for convolution?

**Comment by hfp** [comment]
There are various routines to copy whatever format into or out of LIBXSMM-DNN's internal formats (NCHWc, KCRSck). Routines exist for all supported type-flavors (as well as modded versions omitting certain transposes).

**Comment by hfp** [comment]
Do you have something specifically in mind with this question, e.g., sample code?

**Comment by hfp** [comment]
I improved getting started with LIBXSMM-DNN and added a [README](https://github.com/libxsmm/libxsmm-dnn#libxsmm-dnn). Though, we just recently transitioned this code base from [LIBXSMM](https://libxsmm.readthedocs.io/#deep-learning) into a separate/this repository.

Thank you for your question, and feel free to raise any issue you might run into!
