### ISSUE TITLE
Jitting fully connected layer on neov1 (gvt3) fails with codegen running out of buffer capacity

### ISSUE THREAD

**Issue by kvoronin-intel** [libxsmm/libxsmm-dnn#7]
Branch: tested sve256_bf16_support/main, both failed.

With `${NUMACTL} ./layer_example ${ITERS} ${MB} 2048 1000 ${FUSE} ${TYPE} ${BN} ${BK} ${BC} ${PREC_BF16} ` added to run_fullyconnected.sh,
execution with line on GVT3
`
LIBXSMM_VERBOSE=-1 OMP_NUM_THREADS=64 USE_BF16=1 ./my_run_fullyconnected.sh bf16 1 64 A 0 64 32 1000
`
fails with an error
```
LIBXSMM ERROR (libxsmm_aarch64_instruction_sve_compute:1301): code generation ran out of buffer capacity (error #90002)!
JIT for TPP delbias_reduce_kernel failed. Bailing...!
```
LIBXSMM_VERSION: feature_gather_scatter_offs_sve256-1.17-3357 (25693469) (haven't checked with main of libxsmm)

The code being jitted is at https://github.com/libxsmm/libxsmm-dnn/blob/main/src/libxsmm_dnn_fc.c#L1232, it's reduction TPP/
```
l_unary_shape = libxsmm_create_meltw_unary_shape( bk, bn, delbias_K, delbias_N, LIBXSMM_DATATYPE_BF16, LIBXSMM_DATATYPE_BF16, LIBXSMM_DATATYPE_F32 );
res.delbias_reduce_kernel = libxsmm_dispatch_meltw_unary_v2( LIBXSMM_MELTW_TYPE_UNARY_REDUCE_X_OP_ADD_NCNC_FORMAT, l_unary_shape, LIBXSMM_MELTW_FLAG_UNARY_REDUCE_COLS );
```

Note: With bk=100 ~ ` LIBXSMM_VERBOSE=-1 OMP_NUM_THREADS=64 USE_BF16=1 ./my_run_fullyconnected.sh bf16 1 64 A 0 64 32 **100** ` the test is passing.
Also passing on x86.

**Comment by egeor** [comment]
Commit in libxsmm/libxsmm@30137fb30665f0b646b3deeea18d9bbf5442dfab in libxsmm resolves this unrolling/code size issue.
